language: python
notifications:
  email: false
python:
  - 3.7.4
install:
  - pipenv install
script:
  - echo "no scripts"
after_success:
#   - bash test-script.sh
  - bash <(curl -s https://scripts.scantist.com/staging/ci-travis.sh)
